---
- name: AWS CLI
  block:
    - name: Download AWS CLI v2
      shell: |
        if ! command -v aws &> /dev/null
        then
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
        fi
      args:
        creates: "/usr/local/bin/aws"

    - name: Install AWS CLI v2
      shell: ./aws/install
      args:
        creates: "/usr/local/bin/aws"

    - name: Cleanup AWS CLI v2 installation files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - aws
        - awscliv2.zip

- name: GCloud
  block:
    - name: Add GCloud GPG key
      shell: |
        curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
      args:
        creates: /usr/share/keyrings/cloud.google.gpg

    - name: Add GCloud repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
        state: present
        filename: google-cloud-sdk.list
        
    - name: Install GCloud CLI
      apt:
        name: google-cloud-cli
        state: present
        update_cache: yes

- name: Kubectl
  block:
    - name: Add GCloud GPG key
      shell: |
        curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
      args:
        creates: /usr/share/keyrings/cloud.google.gpg

    - name: Add Kubernetes repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
        state: present
        filename: kubernetes.list
        
    - name: Install kubectl
      apt:
        name: kubectl
        state: present
        update_cache: yes

- name: Helm
  block:      
    - name: Install Helm
      shell: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
      args:
        creates: /usr/local/bin/helm
            
    - name: Cleanup Helm installation script
      file:
        path: get_helm.sh
        state: absent

- name: Terraform
  block:
    - name: Add Terraform GPG key
      shell: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Add Terraform repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ lsb_release_name }} main"
        state: present
        filename: hashicorp.list
        
    - name: Install Terraform
      apt:
        name: terraform
        state: present
        update_cache: yes
